/**
 * Renew Dental staging inventory — read-only.
 *
 * Counts and samples every table needed for the staging → prod migration.
 * Output is pure read; no writes. Targets whichever Supabase URL is in
 * .env.local (which `new-task.sh` copies from primary — staging by default).
 *
 * Usage:
 *   npx tsx scripts/migration/inventory-staging.ts
 *   npx tsx scripts/migration/inventory-staging.ts --markdown > docs/migration/staging-inventory.md
 */

import { createClient } from '@supabase/supabase-js';
import { config } from 'dotenv';
import { resolve } from 'path';

config({ path: resolve(__dirname, '..', '..', '.env.local') });

const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!url || !key) {
  console.error('Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in .env.local');
  process.exit(1);
}

const projectRef = new URL(url).hostname.split('.')[0];
if (projectRef !== 'zneuygoeorhkuhktmuld') {
  console.error(`Refusing to run: expected staging (zneuygoeorhkuhktmuld), got ${projectRef}`);
  console.error('This script is read-only by design but should only run against staging.');
  process.exit(1);
}

const sb = createClient(url, key, { auth: { autoRefreshToken: false, persistSession: false } });

const asMd = process.argv.includes('--markdown');

async function findPractice() {
  const { data, error } = await sb
    .from('practices')
    .select('id, name, slug, integrations, created_at')
    .ilike('name', '%renew%')
    .limit(5);
  if (error) throw error;
  return data ?? [];
}

type Scope = { table: string; column: 'practice_id' | 'office_id' | 'template_id' | null; via?: string };

const scopes: Scope[] = [
  // Reference tables (practice-scoped)
  { table: 'departments', column: 'practice_id' },
  { table: 'practice_role_types', column: 'practice_id' },
  { table: 'task_types', column: 'practice_id' },
  { table: 'task_categories', column: 'practice_id' },
  { table: 'compliance_types', column: 'practice_id' },
  { table: 'equipment_categories', column: 'practice_id' },
  { table: 'supply_categories', column: 'practice_id' },
  { table: 'rooms', column: 'practice_id' },
  // Practice + office structure
  { table: 'offices', column: 'practice_id' },
  // Templates + children
  { table: 'task_templates', column: 'practice_id' },
  { table: 'checklist_items', column: 'practice_id', via: 'children of task_templates' },
  // Equipment
  { table: 'equipment', column: 'practice_id' },
  // Vendors
  { table: 'vendors', column: 'practice_id' },
  { table: 'vendor_contacts', column: 'practice_id' },
  // Out-of-scope but counted to confirm we're skipping them
  { table: 'practice_members', column: 'practice_id', via: 'OUT OF SCOPE — confirm count' },
  { table: 'profiles', column: null, via: 'OUT OF SCOPE — counted globally' },
  { table: 'tasks', column: 'practice_id', via: 'OUT OF SCOPE — live data, regenerated by template' },
  { table: 'task_checklist_items', column: 'practice_id', via: 'OUT OF SCOPE — children of live tasks' },
  { table: 'teams', column: 'practice_id', via: 'OUT OF SCOPE — user explicitly excluded' },
  { table: 'schedule_events', column: 'practice_id', via: 'OUT OF SCOPE' },
  { table: 'requests', column: 'practice_id', via: 'OUT OF SCOPE' },
  { table: 'training_modules', column: 'practice_id', via: 'OUT OF SCOPE' },
  { table: 'training_progress', column: 'practice_id', via: 'OUT OF SCOPE' },
  { table: 'notifications', column: 'practice_id', via: 'OUT OF SCOPE' },
  { table: 'email_log', column: null, via: 'OUT OF SCOPE — counted globally' },
];

async function countScoped(table: string, column: string | null, practiceId: string): Promise<number | string> {
  let q = sb.from(table).select('id', { count: 'exact', head: true });
  if (column) q = q.eq(column, practiceId);
  const { count, error } = await q;
  if (error) return `ERROR: ${error.message}`;
  return count ?? 0;
}

async function sampleColumns(table: string): Promise<string[]> {
  const { data, error } = await sb.from(table).select('*').limit(1);
  if (error) return [`ERROR: ${error.message}`];
  if (!data || data.length === 0) return ['(empty)'];
  return Object.keys(data[0]);
}

async function main() {
  const lines: string[] = [];
  const log = (s: string) => {
    if (asMd) lines.push(s);
    else console.log(s);
  };

  log(`# Renew Dental — staging inventory`);
  log('');
  log(`- Source: \`${projectRef}\` (staging)`);
  log(`- Generated: ${new Date().toISOString()}`);
  log('');

  log(`## Practices matching "renew"`);
  log('');
  const practices = await findPractice();
  if (practices.length === 0) {
    log('NONE FOUND. Aborting.');
    if (asMd) console.log(lines.join('\n'));
    return;
  }
  log('| id | name | slug | created_at |');
  log('|---|---|---|---|');
  for (const p of practices) {
    log(`| \`${p.id}\` | ${p.name} | ${p.slug ?? '—'} | ${p.created_at} |`);
  }
  log('');

  // Use first match — confirm with user before any prod writes
  const practiceId = practices[0].id;
  log(`Using practice \`${practiceId}\` for scope counts.`);
  log('');

  log(`## Row counts (in scope)`);
  log('');
  log('| table | scope | count | columns |');
  log('|---|---|---:|---|');

  for (const s of scopes) {
    const count = await countScoped(s.table, s.column, practiceId);
    const cols = await sampleColumns(s.table);
    const note = s.via ? ` (${s.via})` : '';
    const colSummary = cols.length > 12 ? `${cols.slice(0, 12).join(', ')} … +${cols.length - 12}` : cols.join(', ');
    log(`| \`${s.table}\` | ${s.column ?? 'global'}${note} | ${count} | ${colSummary} |`);
  }
  log('');

  log(`## practices row (full)`);
  log('');
  const { data: practice } = await sb.from('practices').select('*').eq('id', practiceId).single();
  log('```json');
  log(JSON.stringify(practice, null, 2));
  log('```');
  log('');

  // Equipment FK chase — does any equipment row reference a vendor?
  const { data: eqWithVendor } = await sb
    .from('equipment')
    .select('id, name, vendor_id, team_id')
    .eq('practice_id', practiceId)
    .not('vendor_id', 'is', null);
  log(`## Equipment → vendor FK chase`);
  log('');
  log(`Equipment rows with vendor_id set: **${eqWithVendor?.length ?? 0}**`);
  log('');
  if (eqWithVendor && eqWithVendor.length > 0) {
    const vendorIds = [...new Set(eqWithVendor.map((e) => e.vendor_id))];
    log(`Distinct vendors referenced: **${vendorIds.length}**`);
    const { data: vendors } = await sb.from('vendors').select('id, name').in('id', vendorIds as string[]);
    log('');
    log('| vendor_id | name |');
    log('|---|---|');
    for (const v of vendors ?? []) log(`| \`${v.id}\` | ${v.name} |`);
  }
  log('');

  // Equipment team_id chase
  const { data: eqWithTeam } = await sb
    .from('equipment')
    .select('id, team_id')
    .eq('practice_id', practiceId)
    .not('team_id', 'is', null);
  log(`Equipment rows with team_id set: **${eqWithTeam?.length ?? 0}** (these will be null'd on prod since teams are out of scope)`);
  log('');

  // Template child counts (per template)
  const { data: templates } = await sb
    .from('task_templates')
    .select('id, name, type')
    .eq('practice_id', practiceId);
  log(`## task_templates breakdown`);
  log('');
  log(`Total templates: **${templates?.length ?? 0}**`);
  if (templates && templates.length > 0) {
    const byType: Record<string, number> = {};
    for (const t of templates) byType[t.type] = (byType[t.type] ?? 0) + 1;
    log('');
    log('| type | count |');
    log('|---|---:|');
    for (const [type, n] of Object.entries(byType)) log(`| ${type} | ${n} |`);
  }
  log('');

  if (asMd) console.log(lines.join('\n'));
}

main().catch((e) => {
  console.error('Inventory failed:', e);
  process.exit(1);
});
